config/routes.rb
Rails.application.routes.draw do
  get 'errors/not_found'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: "users#index"
  

  get "/login", to: "sessions#new"
  post "/sessions", to: "sessions#create"

  get "/logout", to: "sessions#destroy"

  get "/users", to: "users#index"
  get "/users/new", to: "users#new", as: "new_user"
  get "/users/:id", to:"users#show", as: "user"
  post "/users", to: "users#create"
  get "/users/:id/edit", to: "users#edit", as: "edit_user"
  patch "/users/:id", to: "users#update"
  delete "/users/:id", to: "users#destroy", as: "destroy_user"

  get "/posts", to: "posts#index"
  get "/posts/new", to: "posts#new", as: "new_post"
  get "/posts/:id", to: "posts#show", as: "post"
  post "/posts", to: "posts#create"
  get "/posts/:id/edit", to: "posts#edit", as: "edit_post"
  patch "/posts/:id", to: "posts#update"

  delete "/posts/:id", to: "posts#destroy", as: "destroy_post"

  get "/cities", to: "cities#index", as: "cities"
  get "/cities/new", to: "cities#new", as: "new_city"
  get "/cities/:id", to: "cities#show", as: "city"

  delete "/cities/:id", to: "cities#destroy", as: "destroy_city"


  resources :users do
    resources :posts
  end

  resources :cities do
    resources :posts
  end

  match "/404", :to => "errors#not_found", :via => :all

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/city.rb
class City < ApplicationRecord
  has_many :posts, dependent: :destroy
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user, optional: true
  belongs_to :city, optional: true

  validates :title, length: { in:1..200 }
  validates :body, length: { minimum: 1 }
end

app/models/user.rb
class User < ApplicationRecord
  has_secure_password
  has_many :posts, dependent: :destroy
  def self.confirm(params)
    @user = User.find_by({email: params[:email]})
    @user ? @user.authenticate(params[:password]) : false
  end
  validates :email, uniqueness:true

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  include SessionsHelper
end

app/controllers/cities_controller.rb
class CitiesController < ApplicationController
  def index
    @cities = City.all
  end

  def new
    @city = City.new
    if !admin
      redirect_to cities_path
    end
  end


  def show
    @city = City.find_by_id(params[:id])
  end

  def create
    @city = City.create(city_params)
    redirect_to city_path(@city)
  end

  def destroy
    city_id = params[:id]
    @city = City.find_by_id(city_id)
    @city.delete
    redirect_to cities_path
  end

  private
  def city_params
    params.require(:city).permit(:name, :image)
  end
end

app/controllers/errors_controller.rb
class ErrorsController < ApplicationController
  def not_found
    render(:status => 404)
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController

  def index
    @posts = Post.all
    if !admin
      redirect_to root_path
    end
  end

  def new
    @post = Post.new
    @city = City.find_by_id(params[:city_id])
    if !current_user
      redirect_to posts_path
    elsif !@city
      redirect_to user_path(current_user)
    end
  end

  def create
  current_city = City.find_by_id(params[:city_id])
    if !current_user
      redirect_to login_path
    elsif !current_city
      redirect_to user_path(current_user)
    else
      @post = Post.new(post_params)
      if @post.save

        current_user.posts << @post if current_user
        current_city.posts << @post if current_city

        redirect_to city_post_path(current_city,@post)
      else
        flash[:error]= @post.errors.full_messages
        render :new
      end
    end
  end

  def show
  @post = Post.find_by_id(params[:id])
  @user = User.find_by_id(@post.user_id)
  @city = City.find_by_id(@post.city_id)
  end

  def edit
    post_id = params[:id]
    @post = Post.find_by_id(post_id)
  end

  def update
    post_id = params[:id]
    current_city = City.find_by_id(params[:city_id]) || nil
    @post = Post.find_by_id(post_id)
    if @post.update_attributes(post_params)
     if current_city
       redirect_to city_post_path(current_city, @post)
     else
       redirect_to post_path(@post)
     end

   else
     flash[:error]= @post.errors.full_messages
     render :edit
   end
  end

  def destroy
    post_id = params[:id]
    @post = Post.find_by_id(post_id)
    current_city = City.find_by_id(params[:city_id])
    @post.delete
    user_id = current_user.id
    if params[:city_id]
      redirect_to city_path(params[:city_id])
    else
      redirect_to user_path(user_id)
    end
  end

  private

  def post_params
    params.require(:post).permit(:title, :body)
  end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
    @user = User.new
    render :new
  end

  def create
    user_params = params.require(:user).permit(:email, :password)
    @user = User.confirm(user_params)
    if @user
      login(@user)
      flash[:notice] = "Successfully logged in as #{@user.name}!"
      redirect_to @user
    else
      flash[:error] = "There was an error logging in."
      redirect_to login_path
    end
  end

  def destroy
    session[:user_id]=nil
    flash[:notice]= "Successfully logged out."
    redirect_to root_path
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def index
    @users = User.all
  end

  def new
    @user = User.new
  end

  def create
    @user = User.create(user_params)

    if @user.save

      login(@user)
      redirect_to user_path(@user)
  else

    flash[:error]= @user.errors.full_messages
    render :new
  end


  end

  def show
    @user = User.find_by_id(params[:id])
  end

  def edit
    user_id = params[:id]
    @user = User.find_by_id(user_id)

    if @user != current_user
      redirect_to user_path(@user)
    end
  end

  def update
    user_id = params[:id]
    user = User.find_by_id(user_id)
    user.update_attributes(user_params)
    redirect_to user_path(user)
  end

  def destroy
    @user = User.find_by_id params[:id]
    @user.destroy
    redirect_to root_path
  end

  private
  def user_params
    params.require(:user).permit(:name, :current_city, :email, :password)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper

def bootstrap_class_for flash_type
  case flash_type.to_s
    when 'success'
      "alert-success"
    when "error"
      "alert-warning"
    when "alert"
      "alert-block"
    when "notice"
      "alert-info"
    else
      flash_type.to_s
  end
end


end

app/helpers/cities_helper.rb
module CitiesHelper
  def current_city
    @current_city ||= City.find_by_id[:city_id]
  end
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/errors_helper.rb
module ErrorsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper

  def login(user)
    session[:user_id] = user.id
    @current_user = user
  end

  def current_user
    @current_user ||= User.find_by_id(session[:user_id])
  end

  def admin
    current_user && current_user.admin
  end

  def logged_in?
    if current_user == nil
      redirect_to new_session_path
    end
  end

  def logout
    @current_user = session[:user_id] = nil
  end

end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/cities/index.html.erb
<h1 class="pageTitle">Explore These Cities</h1><br>
<% if current_user &&admin %>
<div class="button"><%= button_to "Add a new city", new_city_path, method: "get", class: "btn btn-success" %></div>
<% end %>

<br>
  <% @cities.each do |city| %>
    <div>
      <h3 class="cityLink"><%= link_to city.name, city_path(city) %></h3>
    </div>
  <br>
<% end %>

app/views/cities/new.html.erb
<h1 class="pageTitle">Add a New City</h1>

<div class="cityForm">
<%= form_for @city do |f| %>
  <div>
    <%= f.text_field :name, placeholder: "City name", class: "cityInput" %>
  </div><br>
  <div>
    <%= f.text_field :image, placeholder: "Image URL", class: "cityInput" %>
  </div><br>
  <%= f.submit "Add City", class: "btn btn-success" %>
<% end %>
</div>

app/views/cities/show.html.erb
<div>
</div>

<div class="holder">
<h2> <%= @city.try(:name) %></h2>
  <center><%= image_tag @city.image, height: 500, width: 800 %></center><br>
    <% if current_user && admin %>
    <%= button_to 'Delete City', destroy_city_path(@city), method: :delete, data: {confirm: "Are you sure you want to delete #{ @city.name }?"}, class: "btn btn-danger" %>
    <% end %>
</div>
<hr>
<div class="holder">
  <% if current_user %>
    <%= button_to "New Post", new_city_post_path(@city, @post), method: "get", class: "btn btn-info" %>

  <% else %>
    <h3>
     <%= link_to "Log In", login_path %>
     or
     <%= link_to "Sign Up", new_user_path %>
     to add a post
     </h3>
  <% end %>
  <hr>
  <% @city.posts.sort_by{|post| [post['updated_at']]}.reverse.each do |post| %>
    <h3> <%= link_to post.title, city_post_path(@city, post) %></h3>
    <h5> <strong>Posted by:</strong> <%= User.find_by_id(post.user_id).name %> </h5>
    <h5> <strong>Created:</strong> <%= post.created_at %> </h5>
    <h4> <em><%= post.body.length > 180 ? post.body[0,180] << "..." : post.body %></em> </h4>
  <% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>üTravel</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <!-- Latest compiled and minified JavaScript -->
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>
  </head>

  <body>
    <nav class="navbar navbar-static-top">
      <div class="container-fluid">
          <p class="navbar-brand"><%= link_to "üTravel", root_path %></p>
        <ul class="nav navbar-nav navbar-right">
          <% if current_user %>
          <li><%= link_to "Profile", user_path(current_user) %></li>
          <li><%= link_to "Log Out", logout_path %></li>
          <li><%= link_to "Browse Cities", cities_path %></li>

          <% else %>
          <li><%= link_to "Log In", login_path %></li>
          <li><%= link_to "Sign Up", new_user_path %></li>
          <li><%= link_to "Browse Cities", cities_path %></li>

          <% end %>
        </ul>
      </div>
    </nav>

    <% flash.each do |name, msg| %>
    <div class="alert <%= bootstrap_class_for(name) %> fade in">
      <button class="close" data-dismiss="alert">×</button>
      <p><%= msg %></p>
    </div>

    <% end %>
    <%= yield %>
  </body>
</html>

app/views/layouts/errors.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>VagabondApp</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <nav class="navbar navbar-default">
      <div class="container-fluid">
        <div class="navbar-header">
          <p class="navbar-brand">Vagabond</p>
        </div>

        <ul class="nav navbar-nav navbar-right">
          <% if current_user %>
          <li><%= link_to "Profile", user_path(current_user) %></li>
          <li><%= link_to "Log Out", logout_path %></li>


          <% else %>
          <li><%= link_to "Log In", login_path %></li>
          <li><%= link_to "Sign Up", new_user_path %></li>
          <% end %>
        </ul>


      </div>
    </nav>
<%= yield %>
  </body>
</html>

app/views/posts/edit.html.erb
<%= form_for @post do |f| %>
<div>
  <%= f.text_field :title, placeholder: "Post Title" %>
</div>
<div>
  <%= f.text_area :body, placeholder: "Text", size: "100x10" %>
</div>
<%= f.submit "Save Changes" %>
<% end %>

app/views/posts/index.html.erb
<h1>Posts</h1>
<br>
  <% @posts.each do |post| %>
    <div>
      <h3><%= link_to post.title, post_path(post) %></h3>
      <h4> <strong>Posted by:</strong> <%= User.find_by_id(post.user_id).name if post.user_id %> </h5>
      <h4> <strong>City:</strong> <%= City.find_by_id(post.city_id).name if post.city_id %> </h5>
    </div>
  <br>
<% end %>

app/views/posts/new.html.erb
<% if @city %>
<div class="newPostForm">
<h2> New Post For <%= @city.name %> </h2>
<% end %>

<%= form_for [@city, @post] do |f| %>
  <div id="postFormTitle">
    <%= f.text_field :title, placeholder: "Title", size: "50x10" %>
  </div><br>
  <div>
    <%= f.text_area :body, placeholder: "Post body", size: "100x10" %>
  </div><br>
  <%= f.submit "Add Post", class: "btn btn-success" %>
<div>
<% end %>

app/views/posts/show.html.erb
<div class="post container">
  <div class="row">
    <div class="col-xs-8">
    <div>
      <small><%= link_to @user.name, user_path(@post.user_id) %>
      <%= " from " + @user.current_city if User.find_by_id(@post.user_id).current_city %></small>
    </div>
      <h2 class="post-head"><%= @post.title %></h2>
    </div>
    <div class="col-xs-4">
      <small>Created <%= @post.created_at.localtime.to_formatted_s(:long_ordinal) %></small>
      <br>
      <small><%= "Edited " + @post.updated_at.localtime.to_formatted_s(:long_ordinal) if @post.updated_at.to_s != @post.created_at.to_s %></small>
    </div>
  </div>
  <p>
    <%= link_to @city.name, city_path(@city.id) if @city %>
  </p>
  <div>
  <p><%= @post.body %></p>
  </div>
  <br>
  <div class="button-area">
  <% if @user == current_user %>
    <%= button_to "Edit Post", edit_post_path, method: "get" %>
  <% end %>
  <% if @user == current_user  ||admin %>
    <%= button_to 'Delete Post', destroy_post_path(@post), method: :delete, data: {confirm: "Are you sure you want to delete #{ @post.title }?"} %>
  <% end %>
  <br>
  </div>
</div>

app/views/users/edit.html.erb
<div class="m-x-auto newuser" id="signupCard">
<h3 class="card-title">Edit User</h3>
<% if @user.id == current_user.id %>
<%= form_for @user do |f| %>
  <div>
    <h5>Edit Name</h5>
    <span class="label label-default"></span><%= f.text_field :name, :class => "fnameSup", placeholder: "Full Name" %>
  </div>
  <div>
    <h5>Edit Current City</h5>
    <span class="label label-default"></span><%= f.text_field :current_city, :class => "citySup", placeholder: "Current City" %>
  </div>
  <div>
    <h5>Edit Email</h5>
    <span class="label label-default"></span><%= f.text_field :email, :class => "emailSup", placeholder: "Email" %>
  </div>

  <%= f.submit "Save User Changes", :class => 'btn-primary', :id => 'saveChange' %>
<% end %>
<% else %>
Something messed up :(
<% end %>
</div>

app/views/users/index.html.erb
<center>
<div class="module top">
    <h2>Learn about different cities from other people's travel experiences.</h2>
</div>

<center>

<% if admin %>
<div class="container">
  <h2>Admin Tools</h2>
  <br>
  <h3><%= link_to "All Posts", posts_path %>
  <h3>Users:</h3>
  <% @users.each do |user| %>
  <h3><%= link_to user.name, user_path(user) %> </h3>
  <% end %>
</div>
<% end %>

app/views/users/new.html.erb
<div class="m-x-auto newuser" id="signupCard">
<h3 class="card-title">Sign Up</h3>
<%= form_for @user do |f| %>
  <div>
    <h5>Full Name</h5>
    <span class="label label-default"></span><%= f.text_field :name, :class => "fnameSup", placeholder: "Full Name" %>
  </div>
  <div>
    <h5>Current City</h5>
    <span class="label label-default"></span><%= f.text_field :current_city, :class => "citySup", placeholder: "Current City" %>
  </div>
  <div>
    <h5>Email</h5>
    <span class="label label-default"></span><%= f.text_field :email, :class => "emailSup", placeholder: "Email" %>
  </div>
  <div>
    <h5>Password</h5>
    <span class="label label-default"></span><%= f.password_field :password, :class => "pwordSup", placeholder: "Password" %>
  </div>
  <%= f.submit "Sign Up", :class => 'btn-primary' %>
<% end %>
</div>

app/views/users/show.html.erb
<center><div class="card" id="userShow">
  <div class="card-block">
  <h4> Username: <%= @user.name %></h4>
  <br>
  Most recent city of residence: <%= @user.current_city %>
  <br>
  <h5>Joined <%= @user.created_at.localtime.to_formatted_s(:long_ordinal) %></h5>
  <% if @user == current_user %>
    <%= button_to "Edit Profile", edit_user_path, method: "get", class: "btn btn-success" %>
    <br>
  <% end %>
  <br>
  <% if current_user && admin %>
    <%= button_to 'Remove User', destroy_user_path(@user), class: "btn btn-success", method: :delete, data: {confirm: "Are you sure you want to delete #{ @user.name }?"}%>
  <% end %>
  <br>
  <h5>Posts:</h5>
  <% if @user.posts.length  < 1 %>
    <%= @user == current_user ? "You have no posts yet!" : "This user has no posts" %>
  <% end %>
  <% @user.posts.sort_by{|post| [post['updated_at']]}.reverse.each do |post| %>
    <h3> <%= link_to post.title, user_post_path(@user, post) %> </h3>
  <% end %>

  </div>
</div>